/**
 * FinalbackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';
import { Shope } from './shope';

export interface Category { 
    id?: number;
    name?: string;
    photo?: string;
    shopeId?: number;
    shope?: Shope;
    items?: Array<Item>;
}