/**
 * FinalbackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { ItemDescraption } from './itemDescraption';
import { ItemPhoto } from './itemPhoto';

export interface Item { 
    id?: number;
    name?: string;
    descraption?: string;
    price?: string;
    categoryId?: number;
    category?: Category;
    itemPhotoId?: number;
    itemPhoto?: ItemPhoto;
    itemDescraptions?: Array<ItemDescraption>;
}